version: "3"
services:
  postgresql:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: pose/docker-postgres
    container_name: docker-postgres
    restart: unless-stopped
    volumes:
      - ./docker/database/postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - pose
  discovery:
    build:
      context: ./server/discovery-server
      dockerfile: Dockerfile
    image: pose/micro/dicovery
    container_name: docker-micro-dicovery
    restart: unless-stopped
    volumes:
      - ./docker/micro/dicovery/logs:/docker/server/discovery-server/logs
    ports:
      - "8761:8761"
    networks:
      - pose
  gateway:
    build:
      context: ./server/gateway-proxy
      dockerfile: Dockerfile
    image: pose/micro/service/gateway
    container_name: docker-micro-gateway-proxy
    restart: unless-stopped
    volumes:  
      - ./docker/micro/gateway/logs:/docker/server/gateway-proxy/logs
    environment:
      - EUREKA_URI=http://discovery:8761/eureka/
    links:
      - discovery
    depends_on:
      - discovery
    ports:
      - "8080:8080"
    networks:
      - pose
  auth:
    build:
      context: ./server/auth-service
      dockerfile: Dockerfile
    image: pose/micro/service/auth
    container_name: docker-micro-service-auth
    restart: unless-stopped
    volumes:  
      - ./docker/micro/service/auth/logs:/docker/server/auth-service/logs
    environment:
      - EUREKA_URI=http://discovery:8761/eureka/
      - PSQL_URL=jdbc:postgresql://postgresql:5432/postgres
    links:
      - postgresql
      - discovery
      - gateway
    depends_on:
      - discovery
      - postgresql
      - gateway
    ports:
      - "8000:8000"
    networks:
      - pose
  employee:
    build:
      context: ./server/employee-service
      dockerfile: Dockerfile
    image: pose/micro/service/employee
    container_name: docker-micro-service-employee
    restart: unless-stopped
    volumes:
      - ./docker/micro/service/employee/logs:/docker/server/employee-service/logs
    environment:
      - EUREKA_URI=http://discovery:8761/eureka/
      - PSQL_URL=jdbc:postgresql://postgresql:5432/postgres
    links:
      - postgresql
      - discovery
      - gateway
    depends_on:
      - discovery
      - postgresql
      - gateway
    # ports:
    #   - "8001:8001"
    networks:
      - pose
  # tasks:
  #   build:
  #     context: ./server/task-service
  #     dockerfile: Dockerfile
  #   image: pose/micro/service/task
  #   container_name: docker-micro-service-task
  #   restart: unless-stopped
  #   volumes:
  #     - ./docker/micro/service/employee/logs:/docker/server/task-service/logs
  #   environment:
  #     - EUREKA_URI=http://discovery:8761/eureka/
  #     - PSQL_URL=jdbc:postgresql://postgresql:5432/postgres
  #   links:
  #     - postgresql
  #     - discovery
  #   depends_on:
  #     - discovery
  #     - postgresql
  #   ports:
  #     - "8002:8002"
  #   networks:
  #     - pose
  # client:
  #   build:
  #     context: ./src/client/
  #     dockerfile: Dockerfile
  #   image: pose/client-reactjs
  #   container_name: client-reactjs
  #   restart: unless-stopped
  #   links:
  #     - gateway
  #   depends_on: 
  #     - gateway
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - pose
  # nginx:
  #   build:
  #     context: ./src/nginx/
  #     dockerfile: Dockerfile
  #   image: pose/nginx
  #   container_name: nginx
  #   restart: unless-stopped
  #   links:
  #     - client
  #   ports:
  #     - "80:80"
  #   networks:
  #     - pose
networks:
  pose:
    driver: bridge
