version: "3"
services:
  docker-postgres:
    build:
      context: ./database/database
      dockerfile: Dockerfile
    image: postgres
    container_name: docker-postgres
    restart: unless-stopped
    volumes:
      - ./logs/database/postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - ute
  discovery:
    build:
      context: ./server/discovery-server
      dockerfile: Dockerfile
    image: hcmute/server/discovery-server
    container_name: discovery
    restart: unless-stopped
    volumes:
      - ./logs/discovery-server:/server/discovery-server/logs
    ports:
      - "8761:8761"
    networks:
      - ute
  gateway:
    build:
      context: ./server/gateway-proxy
      dockerfile: Dockerfile
    image: hcmute/server/gateway-proxy
    container_name: gateway
    restart: unless-stopped
    volumes:  
      - ./logs/gateway-proxy:/server/gateway-proxy/logs
    environment:
      - EUREKA_URI=http://discovery:8761
      - DOMAIN_NAME=auth
      - NON_SECURE_PORT=8080
    links:
      - discovery
    depends_on:
      - discovery
    ports:
      - "8080:8080"
    networks:
      - ute
  auth:
    build:
      context: ./server/auth-service
      dockerfile: Dockerfile
    image: hcmute/server/auth
    container_name: auth
    restart: unless-stopped
    volumes:  
      - ./logs/auth-service:/server/auth-service/logs
    environment:
      - EUREKA_URI=http://discovery:8761
      - PSQL_URL=jdbc:postgresql://docker-postgres:5432/postgres
      - DOMAIN_NAME=auth
      - NON_SECURE_PORT=8000
    links:
      - discovery
      - gateway
      - docker-postgres
    depends_on:
      - discovery
      - gateway
      - docker-postgres
    ports:
      - "8000:8000"
    networks:
      - ute
  employee:
    build:
      context: ./server/employee-service
      dockerfile: Dockerfile
    image: hcmute/server/employee
    container_name: employee
    restart: unless-stopped
    volumes:
      - ./logs/employee-service:/server/employee-service/logs
    environment:
      - EUREKA_URI=http://discovery:8761
      - PSQL_URL=jdbc:postgresql://docker-postgres:5432/postgres
      - DOMAIN_NAME=employee
      - NON_SECURE_PORT=8001
    links:
      - discovery
      - gateway
      - docker-postgres
    depends_on:
      - discovery
      - gateway
      - docker-postgres
    ports:
      - "8001:8001"
    networks:
      - ute
  projects:
    build:
      context: ./server/project-service
      dockerfile: Dockerfile
    image: hcmute/server/project
    container_name: projects
    restart: unless-stopped
    volumes:
      - ./logs/project-service:/server/project-service/logs
    environment:
      - EUREKA_URI=http://discovery:8761
      - PSQL_URL=jdbc:postgresql://docker-postgres:5432/postgres
      - DOMAIN_NAME=projects
      - NON_SECURE_PORT=8003
    links:
      - discovery
      - gateway
      - docker-postgres
    depends_on:
      - discovery
      - gateway
      - docker-postgres
    ports:
      - "8003:8003"
    networks:
      - ute
  notify:
    build:
      context: ./server/notify-service
      dockerfile: Dockerfile
    image: hcmute/server/notify
    container_name: notify
    restart: unless-stopped
    volumes:
      - ./logs/notify-service:/server/notify-service/logs
    environment:
      - EUREKA_URI=http://discovery:8761
      - PSQL_URL=jdbc:postgresql://docker-postgres:5432/postgres
      - DOMAIN_NAME=notify
      - NON_SECURE_PORT=8004
    links:
      - discovery
      - gateway
      - docker-postgres
    depends_on:
      - discovery
      - gateway
      - docker-postgres
    ports:
      - "8004:8004"
    networks:
      - ute
  webhook:
    build:
      context: ./server/webhook-service
      dockerfile: Dockerfile
    image: hcmute/server/webhook
    container_name: webhook
    restart: unless-stopped
    volumes:
      - ./logs/webhook-service:/server/webhook-service/logs
    environment:
      - EUREKA_URI=http://discovery:8761
      - PSQL_URL=jdbc:postgresql://docker-postgres:5432/postgres
      - DOMAIN_NAME=webhook
      - NON_SECURE_PORT=8005
    links:
      - discovery
      - gateway
      - docker-postgres
    depends_on:
      - discovery
      - gateway
      - docker-postgres
    ports:
      - "8005:8005"
    networks:
      - ute
  wiki:
    build:
      context: ./server/wiki-service
      dockerfile: Dockerfile
    image: hcmute/server/wiki
    container_name: wiki
    restart: unless-stopped
    volumes:
      - ./logs/wiki-service:/server/wiki-service/logs
    environment:
      - EUREKA_URI=http://discovery:8761
      - PSQL_URL=jdbc:postgresql://docker-postgres:5432/postgres
      - DOMAIN_NAME=wiki
      - NON_SECURE_PORT=8006
    links:
      - discovery
      - gateway
      - docker-postgres
    depends_on:
      - discovery
      - gateway
      - docker-postgres
    ports:
      - "8006:8006"
    networks:
      - ute
  # client:
  #   build:
  #     context: ../src/client/
  #     dockerfile: Dockerfile
  #   image: hcmute/client-reactjs
  #   container_name: client-reactjs
  #   restart: unless-stopped
  #   links:
  #     - auth.com
  #     - gateway
  #   depends_on:
  #     - auth.com
  #     - gateway
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - ute
networks:
  ute:
    driver: bridge
  