version: "3"
services:
  database:
    build:
      context: ./src/database
      dockerfile: Dockerfile
    image: pose/docker-postgres
    container_name: docker-postgres
    restart: unless-stopped
    volumes:
      - ./src/database/postgresql:/var/lib/postgresql
      - ./src/database/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
