version: "3"
services:
  postgresql:
    build:
      context: ./src/database
      dockerfile: Dockerfile
    image: pose/docker-postgres
    container_name: docker-postgres
    restart: unless-stopped
    # volumes:
    #   - ./logs/database/postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - pose
  discovery:
    build:
      context: ./src/microservice-server/discovery-server
      dockerfile: Dockerfile
    image: pose/service/dicovery
    container_name: docker-micro-dicovery
    restart: unless-stopped
    # volumes:
    #   - ./logs/dicovery-service:/docker/server/discovery-server/logs
    ports:
      - "8761:8761"
    networks:
      - pose
  gateway:
    build:
      context: ./src/microservice-server/gateway-proxy
      dockerfile: Dockerfile
    image: pose/service/gateway
    container_name: docker-micro-gateway-proxy
    restart: unless-stopped
    # volumes:  
    #   - ./logs/gateway-service:/docker/server/gateway-proxy/logs
    environment:
      - EUREKA_URI=http://discovery:8761/eureka/
    links:
      - discovery
    depends_on:
      - discovery
    ports:
      - "8080:8080"
    networks:
      - pose
  auth:
    build:
      context: ./src/microservice-server/auth-service
      dockerfile: Dockerfile
    image: pose/service/auth
    container_name: docker-micro-service-auth
    restart: unless-stopped
    # volumes:  
    #   - ./logs/auth-service:/docker/server/auth-service/logs
    environment:
      - EUREKA_URI=http://discovery:8761/eureka/
      - PSQL_URL=jdbc:postgresql://postgresql:5432/postgres
    links:
      - postgresql
      - discovery
      - gateway
    depends_on:
      - discovery
      - postgresql
      - gateway
    ports:
      - "8000:8000"
    networks:
      - pose
  employee:
    build:
      context: ./src/microservice-server/employee-service
      dockerfile: Dockerfile
    image: pose/service/employee
    container_name: docker-micro-service-employee
    restart: unless-stopped
    # volumes:
    #   - ./logs/employee-service:/docker/server/employee-service/logs
    environment:
      - EUREKA_URI=http://discovery:8761/eureka/
      - PSQL_URL=jdbc:postgresql://postgresql:5432/postgres
    links:
      - postgresql
      - discovery
      - gateway
    depends_on:
      - discovery
      - postgresql
      - gateway
    # ports:
    #   - "8001:8001"
    networks:
      - pose
  tasks:
    build:
      context: ./src/microservice-server/task-service
      dockerfile: Dockerfile
    image: pose/service/task
    container_name: docker-micro-service-task
    restart: unless-stopped
    # volumes:
    #   - ./logs/task-service:/docker/server/task-service/logs
    environment:
      - EUREKA_URI=http://discovery:8761/eureka/
      - PSQL_URL=jdbc:postgresql://postgresql:5432/postgres
    links:
      - postgresql
      - discovery
    depends_on:
      - discovery
      - postgresql
    ports:
      - "8002:8002"
    networks:
      - pose
  projects:
    build:
      context: ./src/microservice-server/project-service
      dockerfile: Dockerfile
    image: pose/service/project
    container_name: docker-micro-service-project
    restart: unless-stopped
    # volumes:
    #   - ./logs/project-service:/docker/server/project-service/logs
    environment:
      - EUREKA_URI=http://discovery:8761/eureka/
      - PSQL_URL=jdbc:postgresql://postgresql:5432/postgres
    links:
      - postgresql
      - discovery
    depends_on:
      - discovery
      - postgresql
    ports:
      - "8003:8003"
    networks:
      - pose
  notify:
    build:
      context: ./src/microservice-server/notify-service
      dockerfile: Dockerfile
    image: pose/service/notify
    container_name: docker-micro-service-notify
    restart: unless-stopped
    # volumes:
    #   - ./logs/notify-service:/docker/server/notify-service/logs
    environment:
      - EUREKA_URI=http://discovery:8761/eureka/
      - PSQL_URL=jdbc:postgresql://postgresql:5432/postgres
    links:
      - postgresql
      - discovery
    depends_on:
      - discovery
      - postgresql
    ports:
      - "8004:8004"
    networks:
      - pose
  request:
    build:
      context: ./src/microservice-server/request-service
      dockerfile: Dockerfile
    image: pose/service/request
    container_name: docker-micro-service-request
    restart: unless-stopped
    # volumes:
    #   - ./logs/request-service:/docker/server/request-service/logs
    environment:
      - EUREKA_URI=http://discovery:8761/eureka/
      - PSQL_URL=jdbc:postgresql://postgresql:5432/postgres
    links:
      - postgresql
      - discovery
    depends_on:
      - discovery
      - postgresql
    ports:
      - "8005:8005"
    networks:
      - pose
  client:
    build:
      context: ./src/client/
      dockerfile: Dockerfile
    image: pose/client-reactjs
    container_name: client-reactjs
    restart: unless-stopped
    # links:
    #   - gateway
    # depends_on: 
      # - gateway
    ports:
      - "3000:3000"
    networks:
      - pose
  nginx:
    build:
      context: ./src/nginx/
      dockerfile: Dockerfile
    image: pose/nginx
    container_name: nginx
    restart: unless-stopped
    links:
      - client
    ports:
      - "80:80"
    networks:
      - pose
networks:
  pose:
    driver: bridge
