spring:
  application:
    name: gateway-proxy
server:
  port: ${PORT:8080}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka
  instance:
    hostname: ${DOMAIN_NAME:localhost}
    nonSecurePort: ${NON_SECURE_PORT:8080}
#    preferIpAddress: true
#Zuul routes. Here for /employee path, we are routing to localhost:8001 with extra path after that.
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
ribbon:
  ReadTimeout: 60000
  connection-timeout: 3000
  eureka:
    enabled: true
zuul:
  routes:
    auth:
      path: /auth/**
      service-id: auth-service
      # By default, all requests to gallery service for example will start with: "/gallery/"
      # What will be sent to the gallery service is what comes after the path defined,
      # So, if request is "/gallery/view/1", gallery service will get "/view/1".
      # In case of auth, we need to pass the "/auth/" in the path to auth service. So, set strip-prefix to false
      strip-prefix: false
      # Exclude authorization from sensitive headers
      sensitive-headers:
      ribbon:
        ReadTimeout: 600000
    emloyees:
      path: /api/employees/**
      strip-prefix: false
      service-id: employee-service
      ribbon:
        ReadTimeout: 600000
    adminemloyees:
      path: /api/admin/employees/**
      strip-prefix: false
      service-id: employee-service
      ribbon:
        ReadTimeout: 600000
    tasks:
      path: /api/tasks/**
      strip-prefix: false
      service-id: project-service
      ribbon:
        ReadTimeout: 600000
    admintasks:
      path: /api/admin/tasks/**
      strip-prefix: false
      service-id: project-service
      ribbon:
        ReadTimeout: 600000
    leadtasks:
      path: /api/lead/tasks/**
      strip-prefix: false
      service-id: project-service
      ribbon:
        ReadTimeout: 600000
    projects:
      path: /api/projects/**
      strip-prefix: false
      service-id: project-service
      ribbon:
        ReadTimeout: 600000
    adminprojects:
      path: /api/admin/projects/**
      strip-prefix: false
      service-id: project-service
      ribbon:
        ReadTimeout: 600000
    requests:
      path: /api/requests/**
      strip-prefix: false
      service-id: notify-service
      ribbon:
        ReadTimeout: 600000
    notify:
      path: /api/notify/**
      strip-prefix: false
      service-id: notify-service
      ribbon:
        ReadTimeout: 600000
    webhook:
      path: /api/webhook/**
      strip-prefix: false
      service-id: webhook-service
      ribbon:
        ReadTimeout: 600000
    adminwebhook:
      path: /api/admin/webhook/**
      strip-prefix: false
      service-id: webhook-service
      ribbon:
        ReadTimeout: 600000
    wiki:
      path: /api/wiki/**
      strip-prefix: false
      service-id: wiki-service
      ribbon:
        ReadTimeout: 600000
    report:
      path: /api/report/**
      strip-prefix: false
      service-id: project-service
      ribbon:
        ReadTimeout: 600000
  host:
    time-to-live: -1
    connect-timeout-millis: 5000
    max-per-route-connections: 10000
    max-total-connections: 5000
    socket-timeout-millis: 6000000
  semaphore:
    max-semaphores: 500