export { default as TaskManagement } from './Staff/TaskManagement.jsx';
export { default as GanttChart } from './Staff/GanttChart.jsx';
export { default as EmployeeManagement } from './HR/EmployeeManagement.jsx';
export { default as Request } from './Common/Request.jsx';
export { default as Notification } from './Common/Notification.jsx';
export { default as ProjectsManagement} from './Staff/ProjectsManagement.jsx';
export { default as TimeKeeping} from './HR/TimeKeeping.jsx';
export {default as Information}from './Common/Infomation.jsx';
export {default as AdminHumanManagement} from './Admin/AdminHumanManagement.jsx';
export {default as AdminDashboard} from './Admin/AdminDashboard.jsx';
export {default as OverviewProject} from './Staff/Project/OverviewProject.jsx';
export {default as ProjectView} from './Staff/Project/ProjectView.jsx';